from individual.go_kegg import go_info_page
from individual.gene import gene_info_page
from individual.mirna import mirna_info_page
from individual.rna import rna_type_page
from individual.spatial import spatial_info_page
from individual.ppi import ppi_info_page
from individual.localization import local_info_page
from individual.orthologs import orthologs_info_page
from individual.snp import snp_info_page
from individual.primer import primer_info_page